// Taiwanese crop types with water coefficients and seasonal factors
export const CROP_TYPES = [
  {
    id: "residential",
    name: "居家電費",
    waterCoefficient: 1.0,
    seasonalFactors: {
      spring: 0.9,
      summer: 1.3,
      autumn: 0.9,
      winter: 1.1,
    },
    description: "",
  },
  {
    id: "rice",
    name: "水稻",
    waterCoefficient: 1.2,
    seasonalFactors: {
      spring: 0.9,
      summer: 1.3,
      autumn: 1.0,
      winter: 0.7,
    },
    description: "",
  },
  {
    id: "leafy_greens",
    name: "葉菜類",
    waterCoefficient: 0.8,
    seasonalFactors: {
      spring: 1.0,
      summer: 1.2,
      autumn: 0.9,
      winter: 0.8,
    },
    description: "",
  },
  {
    id: "root_vegetables",
    name: "根莖類",
    waterCoefficient: 0.9,
    seasonalFactors: {
      spring: 0.95,
      summer: 1.1,
      autumn: 1.0,
      winter: 0.85,
    },
    description: "",
  },
  {
    id: "citrus",
    name: "柑橘類",
    waterCoefficient: 1.0,
    seasonalFactors: {
      spring: 1.1,
      summer: 1.4,
      autumn: 0.9,
      winter: 0.6,
    },
    description: "",
  },
  {
    id: "mango",
    name: "芒果",
    waterCoefficient: 1.1,
    seasonalFactors: {
      spring: 1.2,
      summer: 1.5,
      autumn: 0.8,
      winter: 0.5,
    },
    description: "",
  },
  {
    id: "banana",
    name: "香蕉",
    waterCoefficient: 1.3,
    seasonalFactors: {
      spring: 1.0,
      summer: 1.4,
      autumn: 1.1,
      winter: 0.9,
    },
    description: "",
  },
  {
    id: "pineapple",
    name: "鳳梨",
    waterCoefficient: 1.0,
    seasonalFactors: {
      spring: 1.2,
      summer: 1.3,
      autumn: 0.8,
      winter: 0.6,
    },
    description: "",
  },
  {
    id: "lychee",
    name: "荔枝",
    waterCoefficient: 1.1,
    seasonalFactors: {
      spring: 1.1,
      summer: 1.5,
      autumn: 0.7,
      winter: 0.5,
    },
    description: "",
  },
  {
    id: "guava",
    name: "番石榴",
    waterCoefficient: 1.0,
    seasonalFactors: {
      spring: 1.1,
      summer: 1.2,
      autumn: 0.9,
      winter: 0.8,
    },
    description: "",
  },
];
